apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9292
